title: Generic Page
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          fields:
            header.title:
              replace@: true
            content:
              replace@ true
            header.media_order:
              replace@: true
            _Headings_Section:
              type: section
              underline: true
              title: EDITORIAL.ADMIN.DEFAULT.HEADINGS_SECTION
            _Headings:
              type: columns
              fields:
                _Title:
                  type: column
                  fields:
                    header.title:
                      type: text
                      autofocus: true
                      style: vertical
                      label: PLUGIN_ADMIN.TITLE
                _Subtitle:
                  type: column
                  fields:
                    header.subtitle:
                      type: text
                      style: vertical
                      label: EDITORIAL.ADMIN.DEFAULT.HEADER_SUBTITLE
                _TitleToggle:
                  type: column
                  fields:
                    header.show_title:
                      type: toggle
                      style: vertical
                      label: EDITORIAL.ADMIN.DEFAULT.SHOW_TITLE
                      help: EDITORIAL.ADMIN.DEFAULT.SHOW_TITLE_HELP
                      default: 1
                      highlight: 1
                      options:
                        1: PLUGIN_ADMIN.YES
                        0: PLUGIN_ADMIN.NO
            _Content_Section:
              type: section
              underline: true
              title: EDITORIAL.ADMIN.DEFAULT.CONTENT_SECTION
            header.page_index:
              type: toggle
              style: vertical
              label: EDITORIAL.ADMIN.DEFAULT.PAGE_INDEX
              help: EDITORIAL.ADMIN.DEFAULT.PAGE_INDEX_HELP
              default: 0
              highlight: 0
              options:
                1: PLUGIN_ADMIN.YES
                0: PLUGIN_ADMIN.NO
            _ContentOptions:
              type: column
              fields:
                 content:
                  type: markdown
                  validate:
                    type: textarea
            _Media_Section:
              type: section
              underline: true
              title: EDITORIAL.ADMIN.DEFAULT.IMAGE_OPTIONS      
            _MediaOptions:
              type: columns
              fields:
                _MediaContent:
                  type: column
                  fields:
                    header.media_order:
                      type: pagemedia
                      label: PLUGIN_ADMIN.PAGE_MEDIA
                _ImageOptions:
                  type: column
                  fields:
                    header.show_pageimage:
                      type: toggle
  
                      label: EDITORIAL.ADMIN.DEFAULT.SHOW_PAGEIMAGE
                      help: EDITORIAL.ADMIN.DEFAULT.SHOW_PAGEIMAGE_HELP
                      default: 1
                      highlight: 1
                      options:
                        1: PLUGIN_ADMIN.YES
                        0: PLUGIN_ADMIN.NO
                      validate:
                        type: bool
                    header.featured_image:
                      ordering@: header.subtitle
                      size: large
                      type: pagemediaselect
                      label: EDITORIAL.ADMIN.DEFAULT.FEATURED_IMAGE.LABEL
                      help: EDITORIAL.ADMIN.DEFAULT.FEATURED_IMAGE.HELP
                      preview_images: true
                    header.image_width:
                      type: number
                      label: EDITORIAL.ADMIN.DEFAULT.FEATURED_IMAGE.WIDTH
                      size: small
                      default: 1000
                    header.image_height:
                      type: number
                      label: EDITORIAL.ADMIN.DEFAULT.FEATURED_IMAGE.HEIGHT
                      size: small
                      default: 300