title: Generic Page
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          fields:
             header.primaryImage:
              type: pagemediaselect
              label: 'Primary Image'
              preview_images: true